// amap-trip · HTML 地图模板（可折叠点位面板 + 加载诊断）
// 依赖：高德 JSAPI v2（webapi.amap.com/loader.js），Web端 key + 安全密钥从 .env 读取。

export function buildMapHtmlV2(o) {
  const esc = (s) => String(s).replace(/[<>]/g, '')
  const json = (v) => JSON.stringify(v).replace(/</g, '\\u003c')
  const css = [
    'html,body{margin:0;height:100%;font:13px/1.6 system-ui,-apple-system,"PingFang SC","Microsoft YaHei",sans-serif}',
    '#map{position:absolute;inset:0}',
    '#toggle{position:fixed;top:12px;left:12px;z-index:20;border:0;border-radius:20px;padding:8px 14px;background:#1a73e8;color:#fff;font-size:13px;cursor:pointer;box-shadow:0 2px 8px rgba(0,0,0,.25)}',
    '#panel{position:fixed;top:56px;left:12px;z-index:19;width:300px;max-height:64vh;overflow:auto;background:rgba(255,255,255,.97);padding:10px 12px;border-radius:10px;box-shadow:0 2px 12px rgba(0,0,0,.18);transition:transform .15s ease,opacity .15s ease}',
    '#panel.hidden{transform:translateX(-120%);opacity:0;pointer-events:none}',
    '#panel h3{margin:0 0 6px;font-size:14px}',
    '#meta{color:#666;font-size:12px;margin-bottom:6px}',
    '#list{padding-left:18px;margin:6px 0 0}',
    '#list li{margin:2px 0;cursor:pointer}',
    '#list li:hover{color:#1a73e8;text-decoration:underline}',
    '#diag{display:none;margin:6px 0;padding:6px 8px;border-radius:6px;background:#fff4f4;color:#b3261e;font-size:12px;white-space:pre-wrap}',
    '#hint{margin-top:8px;color:#888;font-size:11px;line-height:1.5}'
  ].join('')
  const S = [
    '<!doctype html>',
    '<html lang="zh-CN">',
    '<head>',
    '<meta charset="utf-8">',
    '<meta name="viewport" content="width=device-width,initial-scale=1">',
    '<title>' + esc(o.title) + '</title>',
    '<style>' + css + '</style>',
    '<script>window._AMapSecurityConfig = { securityJsCode: ' + json(o.sec) + ' }</script>',
    '<script src="https://webapi.amap.com/loader.js?v=2.0&key=' + encodeURIComponent(o.key) + '"></script>',
    '</head>',
    '<body>',
    '<div id="map"></div>',
    '<button id="toggle">点位清单 ▸</button>',
    '<div id="panel" class="hidden">',
    '  <h3>' + esc(o.title) + '</h3>',
    '  <div id="meta"></div>',
    '  <div id="diag"></div>',
    '  <ol id="list"></ol>',
    '  <div id="hint">地图空白常见原因：① JSAPI key 的域名白名单不含本地文件（用 <code>file://</code> 打开时无 Referer）——建议用本地 HTTP 打开；② 网络无法访问 webapi.amap.com。点位为登记地址，现场需核实。</div>',
    '</div>',
    '<script>',
    'const ROUTE = ' + json(o.route) + ';',
    'const MARKERS = ' + json(o.markers) + ';',
    'const diag = document.getElementById("diag");',
    'const note = (m) => { diag.style.display = "block"; diag.textContent += (diag.textContent ? "\\n" : "") + m; };',
    'window.addEventListener("error", (e) => { const msg = String(e.message || e.type); if (msg === "Script error.") note("提示：地图 SDK 内部有一条第三方脚本异常（浏览器隐藏了详情，通常不影响出图）"); else note("脚本错误: " + msg) });',
    'window.addEventListener("unhandledrejection", (e) => note("Promise 异常: " + (e.reason && e.reason.message ? e.reason.message : e.reason)));',
    'const panel = document.getElementById("panel");',
    'const toggle = document.getElementById("toggle");',
    'toggle.onclick = () => { panel.classList.toggle("hidden"); toggle.textContent = panel.classList.contains("hidden") ? "点位清单 ▸" : "点位清单 ▾"; };',
    'AMapLoader.load({ key: ' + json(o.key) + ', version: "2.0", plugins: [] }).then((AMap) => {',
    '  AMap.getConfig().appname = "amap-jsapi-skill";',
    '  let map;',
    '  try { map = new AMap.Map("map", { zoom: 12, center: ROUTE[0], viewMode: "2D" }) } catch (e) { note("地图初始化失败: " + e.message); return }',
    '  map.add(new AMap.Polyline({ path: ROUTE, strokeColor: "#1a73e8", strokeWeight: 5, strokeOpacity: 0.9 }));',
    '  window.__m = map;',
    '  let info = null;',
    '  const openAt = (lng, lat, mk, m) => {',
    '    const pos = new AMap.LngLat(lng, lat);',
    '    try { map.setZoomAndCenter(16, pos) } catch (e) { note("缩放失败: " + e.message) }',
    '    try {',
    '      if (!info) info = new AMap.InfoWindow({ offset: new AMap.Pixel(0, -28) });',
    '      info.setContent("<b>" + m.name + "</b><br>" + (m.km ? m.km + " km · " : "") + (m.cat || ""));',
    '      info.open(map, pos);',
    '    } catch (e) { note("信息窗打开失败: " + e.message) }',
    '  };',
    '  const list = document.getElementById("list");',
    '  const parseLoc = (s) => { const a = String(s).split(","); const lng = Number(a[0]), lat = Number(a[1]); return isFinite(lng) && isFinite(lat) ? [lng, lat] : null };',
    '  if (location.protocol === "file:") note("当前以 file:// 打开：高德 SDK 的部分资源用协议相对地址，浏览器会判为无效 URL，底图可能不显示。请用本地 HTTP 打开（例如在同目录执行 python3 -m http.server 8008）。");',
    '  MARKERS.forEach((m) => {',
    '    const ll = parseLoc(m.loc);',
    '    if (!ll) return;',
    '    const mk = new AMap.Marker({ position: new AMap.LngLat(ll[0], ll[1]), title: m.name });',
    '    mk.on("click", () => openAt(ll[0], ll[1], mk, m));',
    '    map.add(mk);',
    '    const li = document.createElement("li");',
    '    li.textContent = (m.km ? m.km + "km " : "") + m.name + (m.cat ? "（" + m.cat + "）" : "");',
    '    li.onclick = () => { panel.classList.add("hidden"); toggle.textContent = "点位清单 ▸"; openAt(ll[0], ll[1], mk, m); };',
    '    list.appendChild(li);',
    '  });',
    '  try {',
    '    const lngs = ROUTE.map((p) => p[0]), lats = ROUTE.map((p) => p[1]);',
    '    map.setBounds(new AMap.Bounds([Math.min.apply(null, lngs), Math.min.apply(null, lats)], [Math.max.apply(null, lngs), Math.max.apply(null, lats)]), false, [40, 40, 40, 40]);',
    '  } catch (e) {',
    '    note("视野定位失败（不影响底图）: " + e.message);',
    '    try { map.setZoomAndCenter(13, ROUTE[0]) } catch (e2) {}',
    '  }',
    '  document.getElementById("meta").textContent = "路线 " + ROUTE.length + " 点 · 标注 " + MARKERS.length + " 个（点击右下按钮展开清单，点击清单可定位）";',
    '  map.on("complete", () => { if (!MARKERS.length) note("没有点位数据：检查喂给 amap_map 的 CSV 是否含 name/location 列。"); });',
    '}).catch((e) => note("地图 SDK 加载失败: " + (e && e.message ? e.message : e)));',
    '</script>',
    '</body>',
    '</html>',
    ''
  ]
  return S.join('\n')
}
